
#include "Led_Interface.h"

ledErrorState Led_Initialize(void)
{
	GPIO_ConfigChannel(CAR_PORT, CAR_GREEN_CHANNEL, OUTPUT);
	GPIO_ConfigChannel(CAR_PORT, CAR_YELLOW_CHANNEL, OUTPUT);
	GPIO_ConfigChannel(CAR_PORT, CAR_RED_CHANNEL, OUTPUT);

	GPIO_ConfigChannel(PEDESTRIANS_PORT, PEDESTRIANS_GREEN_CHANNEL, OUTPUT);
	GPIO_ConfigChannel(PEDESTRIANS_PORT, PEDESTRIANS_YELLOW_CHANNEL, OUTPUT);
	GPIO_ConfigChannel(PEDESTRIANS_PORT, PEDESTRIANS_RED_CHANNEL, OUTPUT);
	return LED_OK;
}

ledErrorState Led_ON(Led_ID led)
{
	switch (led)
	{
	case CAR_GREEN_LED:
		GPIO_WriteChannel(CAR_PORT,CAR_GREEN_CHANNEL,STD_HIGH);
		break;
	case CAR_YELLOW_LED:
		GPIO_WriteChannel(CAR_PORT,CAR_YELLOW_CHANNEL,STD_HIGH);
		break;
	case CAR_RED_LED:
		GPIO_WriteChannel(CAR_PORT,CAR_RED_CHANNEL,STD_HIGH);
		break;
	case PEDESTRIANS_GREEN_LED:
		GPIO_WriteChannel(PEDESTRIANS_PORT,PEDESTRIANS_GREEN_CHANNEL,STD_HIGH);
		break;
	case PEDESTRIANS_YELLOW_LED:
		GPIO_WriteChannel(PEDESTRIANS_PORT,PEDESTRIANS_YELLOW_CHANNEL,STD_HIGH);
		break;
	case PEDESTRIANS_RED_LED:
		GPIO_WriteChannel(PEDESTRIANS_PORT,PEDESTRIANS_RED_CHANNEL,STD_HIGH);
		break;
	}
	return LED_OK;
}


ledErrorState Led_OFF(Led_ID led)
{
	switch (led)
	{
	case CAR_GREEN_LED:
		GPIO_WriteChannel(CAR_PORT,CAR_GREEN_CHANNEL,STD_LOW);
		break;
	case CAR_YELLOW_LED:
		GPIO_WriteChannel(CAR_PORT,CAR_YELLOW_CHANNEL,STD_LOW);
		break;
	case CAR_RED_LED:
		GPIO_WriteChannel(CAR_PORT,CAR_RED_CHANNEL,STD_LOW);
		break;
	case PEDESTRIANS_GREEN_LED:
		GPIO_WriteChannel(PEDESTRIANS_PORT,PEDESTRIANS_GREEN_CHANNEL,STD_LOW);
		break;
	case PEDESTRIANS_YELLOW_LED:
		GPIO_WriteChannel(PEDESTRIANS_PORT,PEDESTRIANS_YELLOW_CHANNEL,STD_LOW);
		break;
	case PEDESTRIANS_RED_LED:
		GPIO_WriteChannel(PEDESTRIANS_PORT,PEDESTRIANS_RED_CHANNEL,STD_LOW);
		break;
	}
	return LED_OK;
}


ledErrorState Toggle_Led(Led_ID led)
{
	switch (led)
	{
	case CAR_GREEN_LED:
		GPIO_FlipChannel(CAR_PORT,CAR_GREEN_CHANNEL);
		break;
	case CAR_YELLOW_LED:
		GPIO_FlipChannel(CAR_PORT,CAR_YELLOW_CHANNEL);
		break;
	case CAR_RED_LED:
		GPIO_FlipChannel(CAR_PORT,CAR_RED_CHANNEL);
		break;
	case PEDESTRIANS_GREEN_LED:
		GPIO_FlipChannel(PEDESTRIANS_PORT,PEDESTRIANS_GREEN_CHANNEL);
		break;
	case PEDESTRIANS_YELLOW_LED:
		GPIO_FlipChannel(PEDESTRIANS_PORT,PEDESTRIANS_YELLOW_CHANNEL);
		break;
	case PEDESTRIANS_RED_LED:
		GPIO_FlipChannel(PEDESTRIANS_PORT,PEDESTRIANS_RED_CHANNEL);
		break;
	}
	return LED_OK;
}
